### ISSUE TITLE
Thermostat HomeKit Display does not respect unit

### ISSUE THREAD

**Issue by naftaly** [jeffschubert/homebridge-daikin-oneplus#42]
**Describe The Bug:**

In the thermostat accessory settings, when the unit is changed to F, the HomeKit display does not respect it, the physical thermostat does however.

**To Reproduce:**
Choose a thermostat in the Home App, go to its accessory settings, change then unit to F and notice it's still in C in the home app display.

**Expected behavior:**
We expect the display to follow the chosen unit.

**Comment by subdigital** [comment]
Same Issue here

**Comment by jeffschubert** [comment]
@naftaly , @subdigital This is expected behavior. That unit setting can only control the units displayed on the physical thermostat (and Daikin app), not the Home app. To change how it displays in the Home app, you'll need to go to the iOS settings and change it there: Settings>General>Language&Region>Temperature
